config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :posts
      resources :admin_users

      root to: "users#index"
    end
  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user
  validates_presence_of :rationale, :date
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :last_name, :first_name

  def full_name
    "#{last_name.upcase}, #{first_name.upcase}"
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin

  def self.admin_types
    %w[AdminUser]
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = 'You are not authorized to access this content'
        redirect_to root_path
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: 'Your post was successfully created'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update post_params
      redirect_to @post, notice: 'Your post was created successfully'
    else
      render :edit
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: 'Entry was deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:date, :rationale, :status)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    'active' if current_page? path
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render 'shared/nav' %>
          <%= yield %>
        </div>
      </div>
    </div>
  <%= js add_gritter flash[:notice], title: 'Overtime notification', sticky: false  %>
    <%= js add_gritter flash[:alert], title: 'Overtime notification', sticky: false  %>
  </body>
</html>

app/views/posts/_form.html.erb
  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
     <% @post.errors.full_messages.each do |message| %>
        <%= js add_gritter(message, title: 'Overtime App notification',sticky: false) %>
     <% end %>
    <% end %>
  <div class="form-group">
    <%= f.label :date, class: 'col-sm-2' %>
    <%= f.date_field :date, class: 'form-control', id: 'email' %>
  </div>
  <div class="form-group">
    <%= f.label :rationale, class: 'col-sm-2' %>
    <%= f.text_area :rationale, class: 'form-control', id: 'rationale' %>
  </div>
  <div class="form-group">
    <%#= collection_radio_buttons :post, :id, Post.all, :status, :status %>
    <%= f.radio_button :status, 'submitted', class: 'form-control', id: 'submitted' %>
    <%= f.label :status, 'Submitted', class: 'col-sm-2' %>

    <%= f.radio_button :status, 'approved', class: 'form-control', id: 'approved' %>
    <%= f.label :status, 'Approved', class: 'col-sm-2' %>

    <%= f.radio_button :status, 'rejected', class: 'form-control', id: 'rejected' %>
    <%= f.label :status, 'Rejected', class: 'col-sm-2' %>
  </div>
  <%= f.submit value: 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.id %></td>
  <td><%= post.date %></td>
  <td><%= post.user.full_name %></td>
  <td><%= truncate post.rationale %></td>
  <td><%= link_to 'Edit', edit_post_path(post), id: "edit_#{post.id}" %></td>
  <td><%= link_to 'Delete', post_path(post), method: :delete,
                  id: "delete_#{post.id}",
                  data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/posts/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts Page</h1>
<table class="table">
  <thead>
  <tr>
    <th>
      #
    </th>
    <th>
      Date
    </th>
    <th>
      User
    </th>
    <th>
      Rationale
    </th>
  </tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Add an Entry</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_nav.html.erb
<div class="logo pt-3">
  <h1>Time Tracker</h1>
</div>
<ul class="nav nav-pills mt-1">
  <li class="nav-item">
    <%= link_to 'Home', root_path, class: "nav-link #{active?(root_path)}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Time Entries', posts_path, class: "nav-link #{active?(posts_path)}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Add New Entry', new_post_path, class: "nav-link #{active?(new_post_path)}", id: 'new_post' %>
  </li>
  <li class="nav-item dropdown ml-md-auto">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">Account</a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
      <%= link_to 'TODO: Admin-Dashboard',  root_path, class: 'dropdown-item' %>
      <%= link_to 'Log in', new_user_session_path, class: 'dropdown-item' %>
      <div class="dropdown-divider">
      </div>
      <%= link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
    </div>
  </li>
</ul>